name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  checkout-and-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

  build-and-test:
    runs-on: ubuntu-latest
    needs: checkout-and-setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test

    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}  # Explicitly setting the environment variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Debug Environment Variables
      run: echo "DOCKER_USERNAME=${{ env.DOCKER_USERNAME }}"  # Debugging step to check if the variable is available

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}  # Using the environment variable
        password: ${{ secrets.DOCKER_PASSWORD }}  # Using the secret for the password

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/mayah-shop-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    env:
      DROPLET_IP: ${{ vars.DROPLET_IP }}
      DROPLET_USER: ${{ vars.DROPLET_USER }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}  # Explicitly setting the environment variable

    steps:
    - name: Print Connection Info
      run: echo "Connecting to ${{ env.DROPLET_IP }}... with ${{ env.DROPLET_USER }}"

    - name: SSH and Pull Latest Code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.DROPLET_IP }}
        username: ${{ env.DROPLET_USER }}
        key: ${{ secrets.DROPLET_PRIVATE_KEY }}
        script: |
          cd /path/to/your/backend/folder
          git pull origin main

    - name: SSH and Deploy Docker Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.DROPLET_IP }}
        username: ${{ env.DROPLET_USER }}
        key: ${{ secrets.DROPLET_PRIVATE_KEY }}
        script: |
          docker pull ${{ env.DOCKER_USERNAME }}/mayah-shop-server:latest
          docker stop mayah-shop-server || true
          docker rm mayah-shop-server || true
          docker run -d --name mayah-shop-server -p 80:4000 ${{ env.DOCKER_USERNAME }}/mayah-shop-server:latest
